- name: "Create technical group: {{ var_technical_account.username }}"
  group:
    name: "{{ var_technical_account.username }}"
    state: present
    gid: "{{ var_technical_account.gid }}"
  when:
    - var_technical_account.gid is defined

- name: "Create user account: {{ var_technical_account.username }}"
  user:
    name:     "{{ var_technical_account.username }}"
    comment:  "{{ var_technical_account.comment }}"
    shell:    "{{ var_technical_account.shell            | default(var_defeault_shell) }}"
    group:    "{{ var_technical_account.gid              | default(omit) }}"
    groups:   "{{ var_technical_account.system_groups    | default(omit) }}"
    uid:      "{{ var_technical_account.uid              | default(omit) }}"
    home:     "{{ var_technical_account.home_path        | default('/home/' + var_technical_account.username ) }}"

- name: Copy ssh keys
  include: copy_ssh_keys.yml
  vars:
    var_home_dirs:        "{{ var_technical_account.home_path        | default('/home/' + var_technical_account.username ) }}"
    var_username:         "{{ var_technical_account.username }}"
    var_public_ssh_key:   "{{ var_technical_account.public_ssh_key   | default(None)  }}"
    var_private_ssh_key:  "{{ var_technical_account.private_ssh_key  | default(None)  }}"
    var_authorized_keys:  "{{ var_technical_account.authorized_keys  | default('[]')  }}"
