Vagrant.configure("2") do |config|

    config.vm.define "ubuntu" do |ubuntu|
      ubuntu.vm.box = "ubuntu/focal64"
      ubuntu.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
      ubuntu.vm.provision "shell", inline: "usermod -a -G sudo vagrant && cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
      ubuntu.vm.network "private_network", ip: "192.168.33.100"
      ubuntu.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = "1"
      end
    end
  
    config.vm.define "centos7" do |centos7|
      centos7.vm.box = "generic/centos7"
      centos7.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
      centos7.vm.provision "shell", inline: "usermod -a -G wheel vagrant && cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
      centos7.vm.network "private_network", ip: "192.168.33.101"
      centos7.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = "1"
      end
    end
  
    config.vm.define "centos8" do |centos8|
        centos8.vm.box = "generic/centos8"
        centos8.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
        centos8.vm.provision "shell", inline: "usermod -a -G wheel vagrant && cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
        centos8.vm.network "private_network", ip: "192.168.33.102"
        centos8.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
          vb.cpus = "1"
        end
      end
  
      config.vm.define "rhel7" do |rhel7|
        rhel7.vm.box = "generic/rhel7"
        rhel7.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
        rhel7.vm.provision "shell", inline: "usermod -a -G wheel vagrant && cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys && yum install -y openssh-server"
        rhel7.vm.network "private_network", ip: "192.168.33.103"
        rhel7.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
          vb.cpus = "1"
        end
      end
  
      config.vm.define "rhel8" do |rhel8|
        rhel8.vm.box = "generic/rhel8"
        rhel8.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
        rhel8.vm.provision "shell", inline: "usermod -a -G wheel vagrant && cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys && yum install -y openssh-server"
        rhel8.vm.network "private_network", ip: "192.168.33.104"
        rhel8.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
          vb.cpus = "1"
        end
      end
  end